### PR TITLE
Flexible metric specification

### PR DESCRIPTION
**Pull request by rburke2233**
This branch has two changes that I need for my work and may be useful for others.

The major change is flexible metric specification. The configuration file now supports the metric.options specification. With this, you can specify the metrics that you want to apply, including user-defined metrics defined as implementing IRatingMetric, IRankingMetric, or IDiversityMetric interfaces. This will be especially a time advantage for ranking metrics, each of which is fairly expensive. The output is now labeled with the specific metrics that are at work in the evaluation run. In addition to the built-in metrics, you can specify, using reflection, any class name, so that users can implement new metrics without recompiling librec. This is the key feature that I needed.

Example output:

Dataset: ...demo\Datasets\FilmTrust\ratings.txt^M
With Setup: cv -k 5 -p on --rand-seed 1 --test-view all^M
Metrics: MAE,MPE,NMAE,Perplexity,RMSE,R_MAE,R_RMSE,TestTime,TrainTime
UserKNN,0.627315,0.724517,0.179233,-1.000000,0.825723,0.615780,0.837108,4077.600000,3159.000000,,50, PCC, 30,'00:03','00:04'

This is a pretty big change in the way the code is organized: there is a new folder librec/metrics in which these classes are defined. I have tested the code against the current master and the evaluation results are exactly the same on the cases I have tested.

The other change I have made is to make the predict and ranking methods public in the Recommender class. The reason for this is to support hybrid recommenders that have other recommenders as components. For example, a user-based and item-based hybrid can be built just be creating the two objects within an enclosing class and delegating the "predict" call to each and then combining the results. This design idea is not possible with the current "protected" level of access.

### CODE REVIEW

**Comment by guoguibing** [comment]
Hi there, 

Thanks for your great work. Please tell me your name and then I can add you as a contributor.

**Comment by rburke2233** [comment]
You�re welcome. Happy to contribute.

Robin Burke

__________________________________________________________
Robin Burke, Professor
College of Computing and Digital Media, DePaul University rburke@cdm.depaul.edu<mailto:rburke@cdm.depaul.edu>

**Comment by guoguibing** [comment]
Wow, Prof. Robin Burke, Thanks for your great contribution.

**Comment by rburke2233** [comment]
Thanks for creating LibRec. It�s a valuable tool and it is great that there is active development around it. My lab is using Librec for some research this summer and I will also be using it in a recommender systems class that I�ll be teaching in the Winter quarter.

I have a question about ranking evaluation, and I want to make sure that I understand how this works in LibRec:

A ranking measure like Prec@5 assumes that the items in the �correctItems� list are items that would be desirable recommendations for the user. However, when I look at the code in Recommender.java, it does not look like the items are filtered based on their user rating. That is, if user 1 rated items 1,2,3,4,5 all with a rating of 1 (the most negative rating) and items 6,7,8,9,10 with ratings of 5 (the most positive rating), then a recommendation list containing exactly 1,2,3,4,5 would be considered exactly the same as one containing items 6..10: Prec@5 = 1.0. Is that correct or is the filtering performed somewhere else in the code? (The documentation says "get positive items from test matrix� which suggests that there is filtering for positive ratings somewhere.) Is there a way to specify the threshold of what is considered a �good� recommendation? I don�t see that in the configuration documentation, but I might have missed it.

Any help appreciated.

Robin

__________________________________________________________
Robin Burke, Professor
College of Computing and Digital Media, DePaul University rburke@cdm.depaul.edu<mailto:rburke@cdm.depaul.edu>

**Pull request merged**
