### PR TITLE
BPR configuration parameters printout in log message

### PR DESCRIPTION
**Pull request by ranlocar**
- binthold does not affect BPRs configuration
- this also fixes the discrepancy between the names of variables, and their values

### CODE REVIEW

**Comment by guoguibing** [comment]
It's better to add binThresh back. It is used for rating binarization.

**Comment by ranlocar** [comment]
That is correct, generally speaking. But I believe in BPR it doesn't affect
the algorithm behavior.

As far as I understand BPR, there's no looking at the ratings, only at
their existence or inexistence. So a user could have ratings of
[1,3,100,10000] or [1,2,2,2] (if binthold was 2, for example) and the
behavior of BPR would be the same.

I'll add it.

**Comment by ranlocar** [comment]
binThold added back

**Comment by guoguibing** [comment]
Thanks.

**Pull request merged**
